export const elementOptions = [
  { z: 19, name: "K" },
  { z: 20, name: "Ca" },
  { z: 21, name: "Sc" },
  { z: 22, name: "Ti" },
  { z: 23, name: "V" },
  { z: 24, name: "Cr" },
  { z: 25, name: "Mn" },
  { z: 26, name: "Fe" },
  { z: 27, name: "Co" },
  { z: 28, name: "Ni" },
  { z: 29, name: "Cu" },
  { z: 30, name: "Zn" },
  { z: 31, name: "Ga" },
  { z: 32, name: "Ge" },
  { z: 33, name: "As" },
  { z: 34, name: "Se" },
  { z: 35, name: "Br" },
  { z: 36, name: "Kr" },

  { z: 37, name: "Rb" },
  { z: 38, name: "Sr" },
  { z: 39, name: "Y" },
  { z: 40, name: "Zr" },
  { z: 41, name: "Nb" },
  { z: 42, name: "Mo" },
  { z: 43, name: "Tc" },
  { z: 44, name: "Ru" },
  { z: 45, name: "Rh" },
  { z: 46, name: "Pd" },
  { z: 47, name: "Ag" },
  { z: 48, name: "Cf" },
  { z: 49, name: "In" },
  { z: 50, name: "Sn" },
  { z: 51, name: "Sb" },
  { z: 52, name: "Te" },
  { z: 53, name: "I" },
  { z: 54, name: "Xe" },

  { z: 55, name: "Cs" },
  { z: 56, name: "Ba" },
  { z: 57, name: "La" },
  { z: 58, name: "Ce" },
  { z: 59, name: "Pr" },
  { z: 60, name: "Nd" },
  { z: 61, name: "Pm" },
  { z: 62, name: "Sm" },
  { z: 63, name: "Eu" },
  { z: 64, name: "Gd" },
  { z: 65, name: "Tb" },
  { z: 66, name: "Dy" },
  { z: 67, name: "Ho" },
  { z: 68, name: "Er" },
  { z: 69, name: "Tm" },
  { z: 70, name: "Yb" },
  { z: 71, name: "Lu" },

  { z: 72, name: "Hf" },
  { z: 73, name: "Ta" },
  { z: 74, name: "W" },
  { z: 75, name: "Re" },
  { z: 76, name: "Os" },
  { z: 77, name: "Ir" },
  { z: 78, name: "Pt" },
  { z: 79, name: "Au" },
  { z: 80, name: "Hg" },
  { z: 81, name: "TI" },
  { z: 82, name: "Pb" },
  { z: 83, name: "Bi" },
  { z: 84, name: "Po" },
  { z: 85, name: "At" },
  { z: 86, name: "Rn" },
];

export const edgeOptions = ["K", "L-1", "L-2", "L-3"];
